name: Linters

on: [push]

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Python Pylin GitHub Action
        uses: DyedykStanislav/write-docker-actions@v1
        with:
          args: pip3 install -r requirements.txt && flake8 .