name: Linters

on:
  pull_request:
    branches: [ master ]
    paths:
      - "**.py"
jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Python Pylin GitHub Action
        uses: DyedykStanislav/own_linter