name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  styles:
    runs-on: ubuntu-18.04
    name: Linting
    steps:
      - uses: actions/checkout@master
      - uses: DyedykStanislav/own_linter
