name: Linting

on: [push]

jobs:
  styles:
    runs-on: ubuntu-18.04
    name: Linting
    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      - name: Django Coverage action
        uses: actions/python-django-coverage-gitHub-action@0.9
        with:
          django-app: 'sample_app'
          minimum-coverage: '86'
